# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-30 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_user', models.CharField(max_length=20)),
                ('To_user', models.CharField(max_length=20)),
                ('words', models.TextField(max_length=400)),
                ('Time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=32)),
                ('category', models.CharField(default=' ', max_length=100)),
                ('context', models.TextField(default=' ', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('content', models.TextField(max_length=1000)),
                ('publish', models.DateTimeField()),
            ],
        ),
    ]
